### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by AisS85** [mudravrik/kidney_analysis#2]
Спасибо! Еще вникну утром. До меня доходит долго. Такой креатинин (426) был у 29го, а не 22го, 282 визит...

**Comment by mudravrik** [comment]
А, да, я забыл, что там часть пациентов не учитывалась из-за 1 визита.

**Comment by AisS85** [comment]
У него не 1 визит был, у меня отмечено как 423.05.2018, 00:54, "Ivan Tsarev" <notifications@github.com>:А, да, я забыл, что там часть пациентов не учитывалась из-за 1 визита.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


-- С уважением,Даабуль Ирина+79167903285

**Comment by mudravrik** [comment]
Да, но судя по дате, у него креатинин 400 на первом визите, так?
Про 1 визит. Я имел в виду, что часть пациентов у меня в таблице удалилась из-за того, что у них был всего 1 визит. Поэтому пациент, который с номером 29 съехал у меня на строчку 22, и я не правильно адресовал к нему.

**Comment by AisS85** [comment]
Ааа, поняла теперь. Да, 426, потом 233, потом 302, потом 198,02, так?12:45, 23 мая 2018 г., Ivan Tsarev <notifications@github.com>:Да, но судя по дате, у него креатинин 400 на первом визите, так?
Про 1 визит. Я имел в виду, что часть пациентов у меня в таблице удалилась из-за того, что у них был всего 1 визит. Поэтому пациент, который с номером 29 съехал у меня на строчку 22, и я не правильно адресовал к нему.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by mudravrik** [comment]
Да, все так.
